site_name: Lyner Lim
site_url: https://lynerlwl.github.io/
docs_dir: src
site_dir: docs
extra_css:
  - extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  # Color scheme
  palette: 
  # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
# extra:
#   generator: false

# nav: 
  # - Home: index.md
  # - Personal: 
  #   - About Me: personal/about.md
  #   - Work Experience: personal/work_experience.md
  # - Research:
  #   - Note: research/note.md
  #   - Project: research/project.md
  #   - Publication:  research/publication.md
  # - Blog:
      # - Reading is hard: reading-is-hard.md
      # - PC DIY 1/3 - Buying hardware: pc-diy-buying-hardware.md
      # - PC DIY 2/3 - Installing hardware: pc-diy-installing-hardware.md
      # - PC DIY 3/3 - Setup machine: pc-diy-setup-machine.md
  # - Technical:
  # - PhD Journey:
  #   - About PhD: phd/1-what-is-phd.md
  #   - What to consider before starting a PhD: phd/2-before-starting-phd.md
  #   - Getting starting of PhD: phd/3-starting-phd.md
  #   - Exploration and Proposal Defense: phd/4-exploration-and-proposal-defense.md

